# Map starts as empty
hall = "Hall []"
study = "Study []"
lounge = "Lounge []"
billiardRoom = "Billiard Room []"
library = "Library []"
conservatory = "Conservatory []"
ballroom = "Ballroom []"
kitchen = "Kitchen []"
diningRoom = "Dining Room []"
basement = "Basement []"